# Generated by Django 5.1.7 on 2025-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konveyor_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
