# Generated by Django 6.0.7 on 2026-07-17 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacylens_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('expertise_areas', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('departing', 'Departing'), ('departed', 'Departed'), ('onboarding', 'Onboarding')], default='active', max_length=20)),
                ('supermemory_container', models.CharField(blank=True, max_length=100)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('architecture', 'Architecture'), ('process', 'Process'), ('tooling', 'Tooling'), ('domain', 'Domain'), ('decision', 'Decision'), ('ownership', 'Ownership'), ('onboarding', 'Onboarding'), ('tribal', 'Tribal Knowledge')], max_length=100)),
                ('status', models.CharField(choices=[('current', 'Current'), ('historical', 'Historical'), ('deprecated', 'Deprecated'), ('undocumented', 'Undocumented'), ('conflicting', 'Conflicting'), ('unverified', 'Unverified')], default='current', max_length=20)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('source_type', models.CharField(choices=[('interview', 'Interview'), ('document', 'Document'), ('code', 'Code'), ('inferred', 'Inferred'), ('manual', 'Manual')], max_length=50)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('supermemory_doc_id', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_facts', to='legacylens_documents.document')),
                ('source_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_facts', to='knowledge.employee')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='knowledge.knowledgefact')),
            ],
            options={
                'verbose_name': 'Knowledge Fact',
                'verbose_name_plural': 'Knowledge Facts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('asked', 'Asked'), ('answered', 'Answered'), ('resolved', 'Resolved'), ('wont_fix', "Won't Fix")], default='detected', max_length=20)),
                ('suggested_question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gaps', to='knowledge.employee')),
                ('related_facts', models.ManyToManyField(blank=True, related_name='related_gaps', to='knowledge.knowledgefact')),
            ],
            options={
                'verbose_name': 'Knowledge Gap',
                'verbose_name_plural': 'Knowledge Gaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('supersedes', 'Supersedes'), ('related', 'Related'), ('depends_on', 'Depends On'), ('contradicts', 'Contradicts'), ('derived_from', 'Derived From'), ('owned_by', 'Owned By')], max_length=30)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge.knowledgefact')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge.knowledgefact')),
            ],
            options={
                'verbose_name': 'Knowledge Relationship',
                'verbose_name_plural': 'Knowledge Relationships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('role_focus', models.CharField(blank=True, max_length=255)),
                ('plan_data', models.JSONField(default=dict)),
                ('progress', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_plans', to='knowledge.employee')),
            ],
            options={
                'verbose_name': 'Onboarding Plan',
                'verbose_name_plural': 'Onboarding Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['category', 'status'], name='idx_fact_category_status'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['source_employee'], name='idx_fact_source_employee'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['confidence_score'], name='idx_fact_confidence'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgerelationship',
            unique_together={('source', 'target', 'relationship_type')},
        ),
    ]
